version: '3.8'

services:
  neo4j:
    image: neo4j:latest
    container_name: new_neo4j
    ports:
      - "7474:7474"  # Neo4j browser
      - "7687:7687"  # Bolt protocol
    restart: unless-stopped
    environment:
      - NEO4J_AUTH=neo4j/Vivasoft  # Neo4j username and password
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use_neo4j_config=true  # Fixed typo (double underscores)
      - NEO4JLABS_PLUGINS=["apoc"]  # Install APOC plugin
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*  # Allow unrestricted APOC procedures
    volumes:
      - ./database_neo4j:/data  # Persist Neo4j data
      - ./plugins:/plugins  # Persist plugins
    networks:
      - my_bridge_network
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "Vivasoft", "RETURN 1;"]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 30s

  app:
    container_name: banckend_app
    build:
      context: ./backend  # Path to your backend Dockerfile
      dockerfile: Dockerfile
    environment:
      - NEO4J_URI=bolt://new_neo4j:7687  # Use Bolt protocol for Neo4j connection
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=Vivasoft
    ports:
      - "5507:5507"  # Expose backend app port
    depends_on:
      neo4j:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - my_bridge_network
    volumes:
      - ./backend:/app  # Mount host's backend folder into /app inside container

networks:
  my_bridge_network:
    driver: bridge
